name: Run Tests

on:
  push:
    branches:
      - master  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - master  # Run tests for pull requests targeting the main branch

jobs:
  test:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Replace with Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Step 4: Set PYTHONPATH for models folder
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/models" >> $GITHUB_ENV

    # Step 5: Run tests
    - name: Run tests
      run: pytest
